Repository farhan7reza7/Projects-Documentation, pull requests merged in 2024-01, with the labels that each got.

#4 updated README.md
  README.md
Labels: documentation, enhancement, good first issue

#17 Update index.html
  docs/index.html
Labels: documentation, enhancement, help wanted, good first issue

#19 Update index.html
  docs/index.html
Labels: documentation, enhancement, help wanted, good first issue

#20 updated github pages for better indexing
  docs/index.html
Labels: documentation, enhancement, help wanted, good first issue

#21 git commit -S -m "updated github pages for better indexing
  index.html
Labels: documentation, enhancement, help wanted, good first issue

#22 updated docs for better indexing
  docs/frontend_src_index.js.html
  docs/global.html
Labels: documentation, enhancement, help wanted, good first issue

#27 Update index.html
  index.html
Labels: documentation, enhancement, help wanted, good first issue

#36 Issue handler
  docs/index.html
Labels: bug, enhancement, help wanted, good first issue
